spring.application.name=java6


# Cấu hình kết nối đến SQL Server
<<<<<<< HEAD
spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=java6;encrypt=true;trustServerCertificate=true
spring.datasource.username=DangHa
spring.datasource.password=123456
=======
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=java6;encrypt=true;trustServerCertificate=true
<<<<<<< HEAD
spring.datasource.username=hoangg
=======
spring.datasource.username=sa
>>>>>>> 37358d1 (hihi)
spring.datasource.password=123
>>>>>>> 620a069c889506686e4c88bbc3d6dc4972edce8f
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

<<<<<<< HEAD
spring.jpa.open-in-view=false
=======
spring.jpa.open-in-view=false
>>>>>>> 620a069c889506686e4c88bbc3d6dc4972edce8f
