spring.application.name=java6


# Cấu hình kết nối đến SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=java6;encrypt=true;trustServerCertificate=true
<<<<<<< HEAD
spring.datasource.username=hoangg
# =======
# spring.datasource.username=sa
>>>>>>> 37358d1 (hihi)
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

spring.jpa.open-in-view=false