spring.application.name=java6
<<<<<<< HEAD
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=java6;encrypt=false
spring.datasource.username=DangHa
spring.datasource.password=123456

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
=======


# Cấu hình kết nối đến SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=java6;encrypt=true;trustServerCertificate=true
spring.datasource.username=hoangg
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

spring.jpa.open-in-view=false
>>>>>>> bc41e6de7dcf108ddbae2c8712cf46502b5f718b
